export const BANDS = [
    "Paramore",
    "The Cure",
    "Radiohead",
    "Spiritbox",
    "David Bowie",
    "Rolo Tomassi",
    "Slowthai",
    "Pinegrove",
    "Hania Rani",
    "Oxis",
    "Björk",
    "Roxette",
    "Mitski",
    "Land of Talk",
    "Rise Against",
    "Tracey Ullman",
    "Planet 1999",
    "Lust for Youth",
    "Scandinavian Star",
    "Dark Rooms",
    "Youth Code",
    "Nicole Dollanganger",
    "Samia",
    "Brutus",
    "Fleetwood Mac",
    "Fred Again..",
    "Memory Motel",
    "Oklou",
    "Adrianne Lenker",
    "The Plot in You",
    "Just Mustard",
    "State Faults",
    "Griselda",
    "Motion City Soundtrack",
    "Press Club",
    "Black Flag",
    "Emma Ruth Rundle",
    "Misfits",
    "Iceage",
    "Soft Kill",
    "Code Orange",
    "Have a Nice Life",
    "The Smashing Pumpkins",
    "Grouper",
    "Makthaverskan",
    "Charlotte de Witte",
    "Sun Kil Moon",
    "Touché Amoré",
    "Semantix",
    "Birds in Row",
    "Any Shoegaze Band",
    "Electric Wizard",
    "Moonchild",
    "Charli XCX",
    "I Hate Models",
    "Knocked Loose",
    "The Beatles",
    "Missing Persons",
    "Martyrdöd",
    "Pulp",
    "Ayelle",
    "HVOB",
    "Julie Christmas",
    "Van Morrison",
    "Pupil Slicer",
    "Blood Command",
    "Face Your Fears",
    "Dirty Beaches",
    "King Crimson",
    "Angel Olsen",
    "Ólafur Arnalds",
    "Daniel Norgren",
    "Martha Argerich",
    "Glassjaw",
    "King Diamond",
    "Abul Mogard",
    "Lady Lamb",
    "Croatian Amor",
    "Deafheaven",
    "Ozzy Osbourne",
]

export function getBands(count: number) {
    return [...BANDS].sort(() => Math.random() - 0.5).slice(0, count)
}
