export const BRAND = "Atelier UI" as const
export const VERSION = "1.0.0" as const
export const PACKAGE_NAME = "atelier-ui" as const
export const REPO_URL = "https://github.com/whatisjery/atelier-ui" as const
export const GIT_DAYS_THRESHOLD = 5 as const
export const DEFAULT_PIXEL_SIZE = 28 as const
export const LOADER_STEPS = [10, 30, 60, 90, 100] as const
export const SUPPORT_EMAIL = "jeremienallet@gmail.com" as const
export const BUY_ME_A_COFFEE_URL = "https://buymeacoffee.com/whatisjery" as const
