export const BRAND = "Atelier UI" as const
export const VERSION = "0.6.0" as const
export const PACKAGE_NAME = "atelier-ui" as const
export const REPO_URL = "https://github.com/whatisjery/atelier-ui" as const
export const GIT_DAYS_THRESHOLD = 20 as const
export const LANDING_REVEAL_DELAY = 1.3 as const
export const DEFAULT_PIXEL_SIZE = 28 as const
export const SUPPORT_EMAIL = "jeremienallet@gmail.com" as const
export const BUY_ME_A_COFFEE_URL = "https://buymeacoffee.com/whatisjery" as const
