import { lazy } from "react"

export const demos: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
    "fluid-distortion": lazy(() => import("./fluid-distortion/fluid-distortion")),
    "pixel-trail": lazy(() => import("./pixel-trail/pixel-trail")),
    "magnetic-dot-grid": lazy(() => import("./magnetic-dot-grid/magnetic-dot-grid")),
    "halftone-glow": lazy(() => import("./halftone-glow/halftone-glow")),
    "pixelated-text": lazy(() => import("./pixelated-text/pixelated-text")),
    "image-trail": lazy(() => import("./image-trail/image-trail")),
    "infinite-gallery": lazy(() => import("./infinite-gallery/infinite-gallery")),
    "text-scramble": lazy(() => import("./text-scramble/text-scramble")),
    "liquid-media": lazy(() => import("./liquid-media/liquid-media")),
    "infinite-parallax": lazy(() => import("./infinite-parallax/infinite-parallax")),
    "elastic-stick": lazy(() => import("./elastic-stick/elastic-stick")),
    "glowing-fog": lazy(() => import("./glowing-fog/glowing-fog")),
    "infinite-zoom": lazy(() => import("./infinite-zoom/infinite-zoom")),
    "scattered-scroll": lazy(() => import("./scattered-scroll/scattered-scroll")),
    "text-roll": lazy(() => import("./text-roll/text-roll")),
    "text-bounce": lazy(() => import("./text-bounce/text-bounce")),
    "dither-flow": lazy(() => import("./dither-flow/dither-flow")),
    "curve-media": lazy(() => import("./curve-media/curve-media")),
    "text-fluid": lazy(() => import("./text-fluid/text-fluid")),
    "clip-reveal": lazy(() => import("./clip-reveal/clip-reveal")),
    "sweep-exit": lazy(() => import("./sweep-exit/sweep-exit")),
    "stripe-wipe": lazy(() => import("./stripe-wipe/stripe-wipe")),
    "lens-media": lazy(() => import("./lens-media/lens-media")),
    "pixel-media": lazy(() => import("./pixel-media/pixel-media")),
    "sphere-gallery": lazy(() => import("./sphere-gallery/sphere-gallery")),
    "pixel-scroll": lazy(() => import("./pixel-scroll/pixel-scroll")),
}
