import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { hasLocale } from "next-intl"
import { setRequestLocale } from "next-intl/server"
import MainNav from "@/components/common/MainNav"
import SideBar from "@/components/features/docs/side-bar/SideBar"
import { routing } from "@/i18n/routing"
import { getDocsTree } from "@/lib/docs"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

type DocsLayoutProps = {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}

export default async function DocsLayout({ children, params }: DocsLayoutProps) {
    const { locale } = await params
    setRequestLocale(locale)

    const sections = getDocsTree(locale)

    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <div className="mx-auto w-full relative flex flex-col">
            <MainNav />

            <div className="flex">
                <SideBar sections={sections} />
                {children}
            </div>
        </div>
    )
}
