import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { hasLocale } from "next-intl"
import { setRequestLocale } from "next-intl/server"
import Footer from "@/components/common/Footer"
import DocSidebar from "@/components/features/docs/DocSidebar"
import DocTopNav from "@/components/features/docs/DocTopNav"
import Border from "@/components/ui/Border"
import { routing } from "@/i18n/routing"
import { getComponentsList, getSidebarData } from "@/lib/docs"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

type DocsLayoutProps = {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}

export default async function DocsLayout({ children, params }: DocsLayoutProps) {
    const { locale } = await params
    setRequestLocale(locale)

    const { menuSections } = getSidebarData(locale)

    const components = getComponentsList(locale).flatMap(({ children }) => children)

    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <>
            <div className="mx-auto max-w-doc-max-w relative w-full flex flex-col">
                <DocTopNav />
                <div className="flex">
                    <DocSidebar
                        activeComponentCount={components.length}
                        menuSections={menuSections}
                    />
                    {children}
                </div>
                <Border direction="horizontal" className="bottom-0" />
            </div>
            <Footer />
        </>
    )
}
