import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { hasLocale } from "next-intl"
import { setRequestLocale } from "next-intl/server"
import Footer from "@/components/common/Footer"
import MainNav from "@/components/common/MainNav"
import DocSidebar from "@/components/features/docs/DocSidebar"
import { routing } from "@/i18n/routing"
import { getComponentsList, getSidebarData } from "@/lib/docs"
import { getPolarCustomer } from "@/lib/polar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

type DocsLayoutProps = {
    children: React.ReactNode
    params: Promise<{ locale: string }>
}

export default async function DocsLayout({ children, params }: DocsLayoutProps) {
    const { locale } = await params
    setRequestLocale(locale)

    const { menuSections } = getSidebarData(locale)

    const components = getComponentsList(locale).flatMap(({ children }) => children)
    const customer = await getPolarCustomer()

    if (!hasLocale(routing.locales, locale)) {
        notFound()
    }

    return (
        <>
            <div className="mx-auto max-w-base-w relative w-full flex flex-col">
                <MainNav />

                <div className="flex pt-offset">
                    <DocSidebar
                        activeComponentCount={components.length}
                        menuSections={menuSections}
                        hasLicense={customer !== null}
                    />
                    {children}
                </div>
            </div>

            <Footer />
        </>
    )
}
