export type TRegistryComponent = {
    name: string
    description: string
    shared: string[]
    files: string[]
    dependencies: string[]
    registryDependencies: string[]
}

export const components: TRegistryComponent[] = [
    {
        name: "fluid-distortion",
        files: ["fluid-distortion.tsx"],
        description: "A fluid distortion effect that follows the cursor.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei", "postprocessing"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "pixel-trail",
        files: ["pixel-trail.tsx"],
        description: "A trail of pixels that follows the cursor.",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "magnetic-dot-grid",
        files: ["magnetic-dot-grid.tsx"],
        description: "A grid of dots that reacts to the cursor.",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "pixelated-text",
        files: ["pixelated-text.tsx"],
        description: "Text that pixelates in and out.",
        shared: ["hooks/use-frame-loop.ts", "hooks/use-render.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "image-trail",
        files: ["image-trail.tsx"],
        description: "A trail of images that follows the cursor.",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
    {
        name: "infinite-gallery",
        files: ["infinite-gallery.tsx"],
        description: "A gallery that loops forever.",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "text-scramble",
        files: ["text-scramble.tsx"],
        description: "Text that scrambles into place.",
        shared: ["hooks/use-frame-loop.ts", "hooks/use-render.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "liquid-media",
        files: ["liquid-media.tsx"],
        description: "An image or video that ripples under the cursor.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-image", "webgl-video"],
    },
    {
        name: "infinite-parallax",
        files: ["infinite-parallax.tsx"],
        description: "Infinite scrolling columns with parallax.",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: ["smooth-scroll"],
    },
    {
        name: "infinite-zoom",
        files: ["infinite-zoom.tsx"],
        description: "An infinite zoom through images.",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
    {
        name: "scattered-scroll",
        files: ["scattered-scroll.tsx"],
        description: "Items that spread apart while scrolling.",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: ["smooth-scroll"],
    },
    {
        name: "text-split",
        files: ["text-split.tsx"],
        description: "A utility that splits text for animation.",
        shared: ["hooks/use-render.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "text-bounce",
        files: ["text-bounce.tsx"],
        description: "Text that bounces away on hover.",
        shared: ["hooks/use-render.ts"],
        dependencies: ["motion"],
        registryDependencies: ["text-split"],
    },
    {
        name: "webgl-portal",
        files: ["webgl-portal.tsx"],
        description: "A shared portal between the DOM and the canvas.",
        shared: [],
        dependencies: [],
        registryDependencies: ["webgl-provider"],
    },
    {
        name: "webgl-provider",
        files: ["webgl-provider.tsx"],
        description: "A single shared WebGL canvas for the whole app.",
        shared: [],
        dependencies: [
            "three",
            "@types/three",
            "@react-three/fiber",
            "@react-three/postprocessing",
            "postprocessing",
            "motion",
        ],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "smooth-scroll",
        files: ["smooth-scroll.tsx"],
        description: "Smooth scrolling for the whole page.",
        shared: [],
        dependencies: ["lenis", "motion"],
        registryDependencies: [],
    },
    {
        name: "webgl-image",
        files: ["webgl-image.tsx"],
        description: "A WebGL plane that mirrors an image.",
        shared: ["hooks/use-pointer-uv.ts", "hooks/use-dom-plane.ts", "lib/object-fit.ts"],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "webgl-video",
        files: ["webgl-video.tsx"],
        description: "A WebGL plane that mirrors a video.",
        shared: ["hooks/use-pointer-uv.ts", "hooks/use-dom-plane.ts", "lib/object-fit.ts"],
        dependencies: ["three", "@types/three", "@react-three/fiber"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "webgl-text",
        files: ["webgl-text.tsx"],
        description: "A WebGL plane that mirrors text.",
        shared: ["hooks/use-render.ts", "hooks/use-pointer-uv.ts", "hooks/use-dom-plane.ts"],
        dependencies: ["three", "@types/three", "@react-three/fiber"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "curve-media",
        files: ["curve-media.tsx"],
        description: "An image or video that bends as you scroll.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-image", "webgl-video", "smooth-scroll"],
    },
    {
        name: "lens-media",
        files: ["lens-media.tsx"],
        description: "An image or video with a cursor-following lens.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-image", "webgl-video"],
    },
    {
        name: "text-fluid",
        files: ["text-fluid.tsx"],
        description: "Text with an animated shimmer and distortion.",
        shared: ["hooks/use-render.ts"],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-text"],
    },
    {
        name: "pixel-media",
        files: ["pixel-media.tsx"],
        description: "An image or video that breaks into pixels under the cursor.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-image", "webgl-video"],
    },
    {
        name: "webgl-scene",
        files: ["webgl-scene.tsx"],
        description: "A viewport with its own scene and camera on the shared canvas.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "sphere-gallery",
        files: ["sphere-gallery.tsx"],
        description: "A gallery of images mapped onto a sphere.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei", "motion"],
        registryDependencies: ["webgl-scene", "webgl-provider"],
    },
    {
        name: "spiral-gallery",
        files: ["spiral-gallery.tsx"],
        description:
            "An infinite carousel of images staggered along a spiraling tube that scrolls indefinitely.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei", "motion"],
        registryDependencies: ["webgl-scene", "webgl-provider"],
    },
    {
        name: "pixel-scroll",
        files: ["pixel-scroll.tsx"],
        description: "A grid of pixels that fills in as you scroll.",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: ["smooth-scroll"],
    },
    {
        name: "orbit-gallery",
        files: ["orbit-gallery.tsx"],
        description: "A gallery of images on rotating rings.",
        shared: [],
        dependencies: ["three", "@types/three", "@react-three/fiber", "@react-three/drei", "motion"],
        registryDependencies: ["webgl-scene", "webgl-provider"],
    },
    {
        name: "edge-bounce",
        files: ["edge-bounce.tsx"],
        description: "A wrapper that bounces away from the cursor on hover.",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
]
