type TRegistryComponent = {
    name: string
    description: string
    shared: string[]
    files: string[]
    pro?: boolean
    dependencies: string[]
    registryDependencies: string[]
}

export const components: TRegistryComponent[] = [
    {
        name: "fluid-distortion",
        files: ["fluid-distortion.tsx"],
        description: "WebGL fluid distortion cursor effect",
        shared: [],
        dependencies: [
            "three",
            "@react-three/fiber",
            "@react-three/drei",
            "@react-three/postprocessing",
            "postprocessing",
        ],
        registryDependencies: [],
    },
    {
        name: "pixel-trail",
        files: ["pixel-trail.tsx"],
        description: "Pixel trail effect",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "magnetic-dot-grid",
        files: ["magnetic-dot-grid.tsx"],
        description: "Magnetic dot grid effect",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "pixelated-text",
        files: ["pixelated-text.tsx"],
        description: "Pixelated text effect",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "image-trail",
        files: ["image-trail.tsx"],
        description: "Image trail effect",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
    {
        name: "infinite-gallery",
        files: ["infinite-gallery.tsx"],
        description: "Infinite gallery effect",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "simple-scramble",
        files: ["simple-scramble.tsx"],
        description: "Simple scramble effect",
        shared: ["hooks/use-frame-loop.ts"],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "liquid-image",
        files: ["liquid-image.tsx"],
        description: "WebGL image with ripple distortion on pointer movement.",
        shared: ["assets/ripple.png"],
        dependencies: ["three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-image"],
    },
    {
        name: "infinite-parallax",
        files: ["infinite-parallax.tsx"],
        description: "Infinite parallax effect",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
    {
        name: "infinite-zoom",
        files: ["infinite-zoom.tsx"],
        description: "Infinite zoom effect",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
    {
        name: "scattered-scroll",
        files: ["scattered-scroll.tsx"],
        description: "Scattered scroll effect",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
    },
    {
        name: "text-roll",
        files: ["text-roll.tsx", "text-roll.css"],
        description: "Text roll effect",
        shared: [],
        dependencies: [],
        registryDependencies: ["text-split"],
    },
    {
        name: "text-split",
        files: ["text-split.tsx"],
        description: "Text split utility",
        shared: [],
        dependencies: [],
        registryDependencies: [],
    },
    {
        name: "halftone-glow",
        files: ["halftone-glow.tsx"],
        description: "Half tone glow effect",
        shared: [],
        dependencies: ["three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: [],
        pro: true,
    },
    {
        name: "elastic-stick",
        files: ["elastic-stick.tsx"],
        description: "Elastic stick effect",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: [],
        pro: true,
    },
    {
        name: "glowing-fog",
        files: ["glowing-fog.tsx"],
        description: "Glowing fog effect",
        shared: [],
        dependencies: ["three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: [],
        pro: true,
    },
    {
        name: "text-bounce",
        files: ["text-bounce.tsx"],
        description: "Text bounce effect on hover",
        shared: [],
        dependencies: ["motion"],
        registryDependencies: ["text-split"],
    },
    {
        name: "dither-flow",
        files: ["dither-flow.tsx"],
        description: "TODO",
        shared: [],
        dependencies: ["three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: [],
        pro: true,
    },
    {
        name: "webgl-portal",
        files: ["webgl-portal.tsx"],
        description: "Shared R3F portal: DOM↔Canvas teleport for WebGL primitives.",
        shared: [],
        dependencies: ["three", "@react-three/fiber"],
        registryDependencies: [],
    },
    {
        name: "webgl-image",
        files: ["webgl-image.tsx"],
        description: "DOM-aligned WebGL plane that mirrors an <img> via the WebglPortal.",
        shared: [],
        dependencies: ["three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "webgl-text",
        files: ["webgl-text.tsx"],
        description: "DOM-aligned WebGL plane that rasterizes text via the WebglPortal.",
        shared: [],
        dependencies: ["three", "@react-three/fiber"],
        registryDependencies: ["webgl-portal"],
    },
    {
        name: "curve-image",
        files: ["curve-image.tsx"],
        description: "Scroll-reactive WebGL image with sine-based vertex displacement.",
        shared: [],
        dependencies: ["three", "@react-three/fiber"],
        registryDependencies: ["webgl-image"],
    },
    {
        name: "text-fluid",
        files: ["text-fluid.tsx"],
        description: "Floating watery text with FBM scatter, caustic light shimmer and water refraction.",
        shared: [],
        dependencies: ["three", "@react-three/fiber", "@react-three/drei"],
        registryDependencies: ["webgl-text"],
    },
]
